const configs = {
    REVALIDATE_TIME: 300,
    AIRTABLE_BASE_URL: process.env.AIRTABLE_BASE_URL,
    AIRTABLE_BASE_ID: process.env.AIRTABLE_BASE_ID,
    AIRTABLE_PERSONAL_ACCESS_TOKEN: process.env.AIRTABLE_PERSONAL_ACCESS_TOKEN,
}

export default configs